# Generated by Django 4.1 on 2022-08-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=150)),
                ('M_name', models.CharField(max_length=150)),
                ('box', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.box')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.master')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gos_number', models.IntegerField(null=True)),
                ('brend', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('vin_number', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.client')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='auto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.auto'),
        ),
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.box'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.master'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.offer'),
        ),
    ]
