# Generated by Django 4.1 on 2022-08-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_auto_options_alter_box_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='brend',
            field=models.CharField(max_length=150, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='gos_number',
            field=models.IntegerField(null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.client', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='vin_number',
            field=models.IntegerField(null=True, verbose_name='ВИН'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.CharField(max_length=150, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='box',
            name='number',
            field=models.CharField(max_length=150, null=True, verbose_name='Номер бокса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='master',
            name='M_name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='master',
            name='box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='master',
            name='speciality',
            field=models.CharField(max_length=150, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='order',
            name='auto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.auto', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.offer', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.status', verbose_name='Статус'),
        ),
    ]
