# Generated by Django 4.1 on 2022-08-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_master_description_master_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSpectr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Услуга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Спектр услуг',
                'verbose_name_plural': 'Спектры услуг',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='photo',
        ),
        migrations.AlterField(
            model_name='master',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.auto', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.offer', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='offer',
            name='spectr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.offerspectr', verbose_name='Спектр услуг'),
        ),
    ]
