# Generated by Django 4.1 on 2022-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_offerspectr_remove_offer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В процессе', 'В процессе'), ('Готово', 'Готово'), ('Закончено', 'Закончено')], default='В обработке', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
