# Generated by Django 4.1 on 2022-08-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['owner'], 'verbose_name': 'Авто', 'verbose_name_plural': 'Авто'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['M_name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастеры'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['title'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='offerspectr',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.master', verbose_name='Мастер'),
        ),
    ]
