# Generated by Django 4.1 on 2022-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_auto_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_find',
            field=models.TextField(blank=True, default='__'),
        ),
    ]
