# Generated by Django 4.1 on 2022-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_to_find'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='gos_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Гос номер'),
        ),
    ]
