# Generated by Django 4.1 on 2022-09-04 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_alter_auto_gos_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='brend',
            field=models.CharField(max_length=150, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_find',
            field=models.CharField(blank=True, default='__', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
