# Generated by Django 4.1 on 2022-09-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_auto_brend_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='data',
            new_name='date',
        ),
    ]
